import type { SupplyStore } from '../domain/SupplyStore.entity';

export const suppliesMock: SupplyStore[] = [
  {
    id: '1',
    name: 'MediSuministros Central',
    address: 'Av. Amazonas N28-75 y Vozandes',
    phone: '+593987700001',
    schedule: 'Lun-Vie 8:30-18:30, Sáb 9:00-13:00',
    image: 'https://via.placeholder.com/400x300/f97316/ffffff?text=MediSuministros',
    products: ['Productos ortopédicos', 'Prótesis', 'Plantillas', 'Fajas', 'Rodilleras', 'Insumos médicos'],
    hasDelivery: true,
    sponsored: false,
  },
  {
    id: '2',
    name: 'Ortopedia y Más',
    address: 'Av. 10 de Agosto N30-120 y Vicente Ramón Roca',
    phone: '+593987700002',
    schedule: 'Lun-Vie 8:00-17:00',
    image: 'https://via.placeholder.com/400x300/f97316/ffffff?text=Ortopedia+Mas',
    products: ['Productos ortopédicos', 'Prótesis', 'Plantillas'],
    hasDelivery: false,
    sponsored: false,
  },
  {
    id: '3',
    name: 'MediEquipos Quito',
    address: 'Av. 12 de Octubre N26-50 y Lincoln',
    phone: '+593987700003',
    schedule: 'Lun-Vie 8:00-18:00, Sáb 9:00-14:00',
    image: 'https://via.placeholder.com/400x300/f97316/ffffff?text=MediEquipos',
    products: ['Insumos médicos', 'Equipos médicos', 'Materiales quirúrgicos'],
    hasDelivery: true,
    sponsored: false,
  },
  {
    id: '4',
    name: 'Ortopedia y Equipos Médicos Del Valle',
    address: 'Av. Eloy Alfaro N29-185 y Alemania',
    phone: '+593987700004',
    schedule: 'Lun-Vie 8:30-18:30, Sáb 9:00-14:00',
    image: 'https://via.placeholder.com/400x300/f97316/ffffff?text=Del+Valle',
    products: ['Productos ortopédicos', 'Prótesis', 'Plantillas', 'Fajas', 'Rodilleras'],
    hasDelivery: true,
    sponsored: false,
  },
  {
    id: '5',
    name: 'MediSupply Ecuador',
    address: 'Av. 6 de Diciembre N34-145 y Checoslovaquia',
    phone: '+593987700005',
    schedule: 'Lun-Sáb 8:00-19:00',
    image: 'https://via.placeholder.com/400x300/f97316/ffffff?text=MediSupply',
    products: ['Insumos médicos', 'Equipos médicos', 'Materiales de curación'],
    hasDelivery: true,
    sponsored: true,
  },
  {
    id: '6',
    name: 'Ortopedia y Suministros del Norte',
    address: 'Av. Eloy Alfaro N32-120 y Japón',
    phone: '+593987700002',
    schedule: 'Lun-Vie 8:30-18:30, Sáb 9:00-13:00',
    image: 'https://via.placeholder.com/400x300/f97316/ffffff?text=Del+Norte',
    products: ['Productos ortopédicos', 'Prótesis', 'Plantillas', 'Fajas', 'Rodilleras', 'Insumos médicos'],
    hasDelivery: true,
    sponsored: false,
  },
];

