import type { User } from "../domain/user.entity";

export const MOCK_USERS: User[] = [
  {
    id: "admin-1",
    name: "Admin General",
    email: "admin@medicones.com",
    role: "ADMIN",
    isActive: true,
    createdAt: "2024-01-01",
  },
  {
    id: "admin-2",
    name: "Admin Secundario",
    email: "admin2@medicones.com",
    role: "ADMIN",
    isActive: true,
    createdAt: "2024-01-15",
  },
  {
    id: "doctor-1",
    name: "Dr. Juan Pérez",
    email: "juan.perez@medicones.com",
    role: "PROVIDER",
    tipo: "doctor",
    isActive: true,
    createdAt: "2024-02-01",
  },
  {
    id: "doctor-2",
    name: "Dr. María González",
    email: "maria.gonzalez@medicones.com",
    role: "PROVIDER",
    tipo: "doctor",
    isActive: true,
    createdAt: "2024-02-05",
  },
  {
    id: "doctor-3",
    name: "Dr. Carlos Mendoza",
    email: "carlos.mendoza@medicones.com",
    role: "PROVIDER",
    tipo: "doctor",
    isActive: true,
    createdAt: "2024-02-08",
  },
  {
    id: "doctor-4",
    name: "Dra. Ana Martínez",
    email: "ana.martinez@medicones.com",
    role: "PROVIDER",
    tipo: "doctor",
    isActive: true,
    createdAt: "2024-02-12",
  },
  {
    id: "doctor-5",
    name: "Dr. Roberto Sánchez",
    email: "roberto.sanchez@medicones.com",
    role: "PROVIDER",
    tipo: "doctor",
    isActive: true,
    createdAt: "2024-02-15",
  },
  {
    id: "pharmacy-1",
    name: "Farmacia Fybeca",
    email: "fybeca@medicones.com",
    role: "PROVIDER",
    tipo: "pharmacy",
    isActive: true,
    createdAt: "2024-02-10",
  },
  {
    id: "pharmacy-2",
    name: "Farmacia Salud Total",
    email: "saludtotal@medicones.com",
    role: "PROVIDER",
    tipo: "pharmacy",
    isActive: true,
    createdAt: "2024-02-18",
  },
  {
    id: "pharmacy-3",
    name: "Farmacia San José",
    email: "sanjose@medicones.com",
    role: "PROVIDER",
    tipo: "pharmacy",
    isActive: true,
    createdAt: "2024-02-22",
  },
  {
    id: "lab-1",
    name: "Laboratorio Clínico Vital",
    email: "labvital@medicones.com",
    role: "PROVIDER",
    tipo: "lab",
    isActive: true,
    createdAt: "2024-02-15",
  },
  {
    id: "lab-2",
    name: "Laboratorio Diagnóstico",
    email: "labdiagnostico@medicones.com",
    role: "PROVIDER",
    tipo: "lab",
    isActive: true,
    createdAt: "2024-02-20",
  },
  {
    id: "lab-3",
    name: "Laboratorio Clínico XYZ",
    email: "labxyz@medicones.com",
    role: "PROVIDER",
    tipo: "lab",
    isActive: true,
    createdAt: "2024-02-25",
  },
  {
    id: "ambulance-1",
    name: "Ambulancias Vida",
    email: "ambulanciasvida@medicones.com",
    role: "PROVIDER",
    tipo: "ambulance",
    isActive: true,
    createdAt: "2024-02-20",
  },
  {
    id: "ambulance-2",
    name: "Ambulancias Rápidas",
    email: "ambulanciasrapidas@medicones.com",
    role: "PROVIDER",
    tipo: "ambulance",
    isActive: true,
    createdAt: "2024-02-25",
  },
  {
    id: "supplies-1",
    name: "Insumos Médicos Plus",
    email: "insumosplus@medicones.com",
    role: "PROVIDER",
    tipo: "supplies",
    isActive: true,
    createdAt: "2024-02-25",
  },
  {
    id: "supplies-2",
    name: "Insumos Médicos ABC",
    email: "insumosabc@medicones.com",
    role: "PROVIDER",
    tipo: "supplies",
    isActive: true,
    createdAt: "2024-02-28",
  },
];

export const getUsersMock = (): User[] => {
  return MOCK_USERS;
};

