// import { httpClient } from '../../../shared/lib/http'; // TODO: Usar cuando se implemente el backend
import type { Pharmacy } from '../domain/Pharmacy.entity';
import type { PharmacyBranch } from '../domain/PharmacyBranch.entity';
import type { Review } from '../domain/Review.entity';

/**
 * API: Obtener lista de farmacias
 * TODO: Conectar con endpoint real del backend cuando esté disponible
 * Endpoint esperado: GET /api/pharmacies
 */
export const getPharmaciesAPI = async (): Promise<Pharmacy[]> => {
  // TODO: Reemplazar con llamada real al backend
  // const response = await httpClient.get<Pharmacy[]>('/pharmacies');
  // return response.data;

  // NOTE: Datos mock por ahora - remover cuando se implemente el backend
  return [
    {
      id: '1',
      name: 'Farmacias Medicity',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/04a14f477_MEDY.png',
      description: 'Farmacia de confianza',
      totalBranches: 3,
      rating: 4.5,
      totalReviews: 120,
    },
    {
      id: '2',
      name: 'Farmacias Fybeca',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/d9555d0a9_FYB.jpg',
      description: 'Somos parte de tu vida',
      totalBranches: 5,
      rating: 4.8,
      totalReviews: 250,
    },
    {
      id: '3',
      name: 'Farmacias Comunitarias',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/903efabd8_COMUN.jpg',
      description: 'Salud para tu comunidad',
      totalBranches: 8,
      rating: 4.6,
      totalReviews: 180,
    },
    {
      id: '4',
      name: 'Farmacias Económicas',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/14c64c21f_FARMY.png',
      description: 'Precios accesibles',
      totalBranches: 12,
      rating: 4.4,
      totalReviews: 320,
    },
    {
      id: '5',
      name: "Pharmacy's",
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/ce9864602_PHARM.png',
      description: 'Ideas llenas de salud',
      totalBranches: 6,
      rating: 4.7,
      totalReviews: 150,
    },
    {
      id: '6',
      name: 'Farmacia El Descuento',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/eea4fc426_DSCT.png',
      description: 'Los mejores precios',
      totalBranches: 4,
      rating: 4.5,
      totalReviews: 95,
    },
    {
      id: '7',
      name: 'Farmacias Sana Sana',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/d711cf216_SANSAN.jpg',
      description: 'Tu salud es nuestra prioridad',
      totalBranches: 7,
      rating: 4.6,
      totalReviews: 210,
    },
    {
      id: '8',
      name: 'Farmacias El Cisne',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/45885ad65_ELCISNE.png',
      description: 'Medicina de especialidad',
      totalBranches: 5,
      rating: 4.8,
      totalReviews: 175,
    },
    {
      id: '9',
      name: 'Farmayor',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/690141bd4_FARMAYOR.png',
      description: 'Tu Farmacéutica',
      totalBranches: 9,
      rating: 4.7,
      totalReviews: 280,
    },
    {
      id: '10',
      name: 'Farmacias Cruz Azul',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/eb24fa6d1_cruA.png',
      description: 'Me cuida',
      totalBranches: 6,
      rating: 4.5,
      totalReviews: 140,
    },
    {
      id: '11',
      name: 'Farmacias San Gregorio',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/49803260b_SANGREGORIO.jpg',
      description: 'Tradición y confianza',
      totalBranches: 4,
      rating: 4.6,
      totalReviews: 110,
    },
    {
      id: '12',
      name: 'Farmacias Salud Total',
      logo: 'https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6902894b32a58f42abc8a50e/3ac376dae_SANTAMARTHA.png',
      description: 'Cuidamos tu bienestar',
      totalBranches: 10,
      rating: 4.7,
      totalReviews: 290,
    },
  ];
};

/**
 * API: Obtener detalle de una farmacia
 * TODO: Conectar con endpoint real del backend cuando esté disponible
 * Endpoint esperado: GET /api/pharmacies/:id
 */
export const getPharmacyAPI = async (id: string): Promise<Pharmacy> => {
  // TODO: Reemplazar con llamada real al backend
  // const response = await httpClient.get<Pharmacy>(`/pharmacies/${id}`);
  // return response.data;

  // NOTE: Datos mock por ahora - buscar en la lista de farmacias
  const pharmacies = await getPharmaciesAPI();
  const pharmacy = pharmacies.find((p) => p.id === id);
  
  if (pharmacy) {
    return pharmacy;
  }

  // Fallback si no se encuentra
  return {
    id,
    name: 'Farmacia',
    logo: 'https://via.placeholder.com/300x200/06b6d4/ffffff?text=Farmacia',
    description: 'Farmacia de confianza',
    totalBranches: 0,
    rating: 0,
    totalReviews: 0,
  };
};

/**
 * API: Obtener sucursales de una farmacia
 * TODO: Conectar con endpoint real del backend cuando esté disponible
 * Endpoint esperado: GET /api/pharmacies/:id/branches
 */
export const getPharmacyBranchesAPI = async (pharmacyId: string): Promise<PharmacyBranch[]> => {
  // TODO: Reemplazar con llamada real al backend
  // const response = await httpClient.get<PharmacyBranch[]>(`/pharmacies/${pharmacyId}/branches`);
  // return response.data;

  // NOTE: Datos mock por ahora - sucursales únicas para cada farmacia
  const branchesByPharmacy: Record<string, PharmacyBranch[]> = {
    '1': [ // Farmacias Medicity
      {
        id: '1-1',
        pharmacyId,
        name: 'Medicity El Condado',
        address: 'Av. Mariana de Jesús E7-50 y Alemania',
        phone: '+593987660042',
        schedule: 'Lun-Dom 8:30-21:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/medicity-07.jpg',
        rating: 4.5,
        totalReviews: 45,
      },
      {
        id: '1-2',
        pharmacyId,
        name: 'Medicity Cumbayá',
        address: 'Vía Interoceánica Km 12.5',
        phone: '+593987660042',
        schedule: 'Lun-Dom 8:30-21:00',
        hasDelivery: true,
        image: 'https://fastly.4sqi.net/img/general/320x240/61607334_pJHR8VPjSpzwPBjtU6GjRzBYk-ly4_76BEyvRjjVkbc.jpg',
        rating: 4.7,
        totalReviews: 38,
      },
      {
        id: '1-3',
        pharmacyId,
        name: 'Medicity La Prensa',
        address: 'Av. La Prensa N58-125 y Galo Plaza',
        phone: '+593987660042',
        schedule: 'Lun-Dom 8:30-21:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/medicity-05.jpg',
        rating: 4.6,
        totalReviews: 37,
      },
    ],
    '2': [ // Farmacias Fybeca
      {
        id: '2-1',
        pharmacyId,
        name: 'Fybeca Quito Centro',
        address: 'Av. Amazonas N34-123 y Atahualpa',
        phone: '+593987660043',
        schedule: 'Lun-Sáb 8:00-20:00, Dom 9:00-18:00',
        hasDelivery: true,
        image: 'https://muchomejorecuador.org.ec/wp-content/uploads/2023/06/1623872634-FYBECA.jpg',
        rating: 4.8,
        totalReviews: 52,
      },
      {
        id: '2-2',
        pharmacyId,
        name: 'Fybeca Cumbayá',
        address: 'Av. Interoceánica y Av. Simón Bolívar',
        phone: '+593987660044',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://imagenes.primicias.ec/files/og_thumbnail/files/fp/uploads/2025/10/24/68fbfeb3da7a8.r_d.1373-953-0.jpeg',
        rating: 4.9,
        totalReviews: 68,
      },
      {
        id: '2-3',
        pharmacyId,
        name: 'Fybeca La Mariscal',
        address: 'Av. 6 de Diciembre N24-123 y Colón',
        phone: '+593987660045',
        schedule: 'Lun-Dom 7:30-22:00',
        hasDelivery: true,
        image: 'https://www.quitoinforma.gob.ec/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-29-at-09.06.39-800x445.jpeg',
        rating: 4.7,
        totalReviews: 41,
      },
      {
        id: '2-4',
        pharmacyId,
        name: 'Fybeca Guayaquil',
        address: 'Av. 9 de Octubre y Malecón',
        phone: '+593987660046',
        schedule: 'Lun-Sáb 8:00-20:00',
        hasDelivery: true,
        image: 'https://ekosnegocios.com/image/posts/November2022/am4hZbtpGFtRo7vyQKfQ.png',
        rating: 4.6,
        totalReviews: 39,
      },
      {
        id: '2-5',
        pharmacyId,
        name: 'Fybeca Cuenca',
        address: 'Av. Gran Colombia y Benigno Malo',
        phone: '+593987660047',
        schedule: 'Lun-Dom 8:00-20:00',
        hasDelivery: false,
        image: 'https://cloudfront-us-east-1.images.arcpublishing.com/eluniverso/Y4SEHAHSYFGHTHWUPOAXWUJMYQ.jpg',
        rating: 4.8,
        totalReviews: 50,
      },
    ],
    '3': [ // Farmacias Comunitarias
      {
        id: '3-1',
        pharmacyId,
        name: 'Comunitaria Norte',
        address: 'Av. 10 de Agosto N30-123 y Mariana de Jesús',
        phone: '+593987660048',
        schedule: 'Lun-Dom 7:00-22:00',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCjeq7EoLVvSjxPaPoODJcKdoJdEph_raFHg&s',
        rating: 4.6,
        totalReviews: 28,
      },
      {
        id: '3-2',
        pharmacyId,
        name: 'Comunitaria Sur',
        address: 'Av. Morán Valverde y Av. Mariscal Sucre',
        phone: '+593987660049',
        schedule: 'Lun-Sáb 8:00-21:00, Dom 9:00-19:00',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCjeq7EoLVvSjxPaPoODJcKdoJdEph_raFHg&s',
        rating: 4.5,
        totalReviews: 32,
      },
      {
        id: '3-3',
        pharmacyId,
        name: 'Comunitaria Centro',
        address: 'Av. Pichincha y Av. 24 de Mayo',
        phone: '+593987660050',
        schedule: 'Lun-Dom 8:00-20:00',
        hasDelivery: false,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCjeq7EoLVvSjxPaPoODJcKdoJdEph_raFHg&s',
        rating: 4.7,
        totalReviews: 35,
      },
      {
        id: '3-4',
        pharmacyId,
        name: 'Comunitaria Valle',
        address: 'Av. Los Shyris y Av. 6 de Diciembre',
        phone: '+593987660051',
        schedule: 'Lun-Dom 7:30-21:30',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCjeq7EoLVvSjxPaPoODJcKdoJdEph_raFHg&s',
        rating: 4.6,
        totalReviews: 29,
      },
      {
        id: '3-5',
        pharmacyId,
        name: 'Comunitaria La Carolina',
        address: 'Av. Naciones Unidas y Av. Shyris',
        phone: '+593987660052',
        schedule: 'Lun-Dom 8:00-22:00',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCjeq7EoLVvSjxPaPoODJcKdoJdEph_raFHg&s',
        rating: 4.8,
        totalReviews: 44,
      },
      {
        id: '3-6',
        pharmacyId,
        name: 'Comunitaria Iñaquito',
        address: 'Av. Amazonas y Av. Naciones Unidas',
        phone: '+593987660053',
        schedule: 'Lun-Sáb 8:00-20:00',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCjeq7EoLVvSjxPaPoODJcKdoJdEph_raFHg&s',
        rating: 4.5,
        totalReviews: 31,
      },
      {
        id: '3-7',
        pharmacyId,
        name: 'Comunitaria Quicentro',
        address: 'Av. 6 de Diciembre y Av. Naciones Unidas',
        phone: '+593987660054',
        schedule: 'Lun-Dom 9:00-21:00',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCjeq7EoLVvSjxPaPoODJcKdoJdEph_raFHg&s',
        rating: 4.7,
        totalReviews: 38,
      },
      {
        id: '3-8',
        pharmacyId,
        name: 'Comunitaria San Rafael',
        address: 'Av. 12 de Octubre y Av. Colón',
        phone: '+593987660055',
        schedule: 'Lun-Dom 8:00-20:00',
        hasDelivery: false,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCjeq7EoLVvSjxPaPoODJcKdoJdEph_raFHg&s',
        rating: 4.6,
        totalReviews: 27,
      },
    ],
    '4': [ // Farmacias Económicas
      {
        id: '4-1',
        pharmacyId,
        name: 'Económicas Norte',
        address: 'Av. 10 de Agosto N45-678',
        phone: '+593987660056',
        schedule: 'Lun-Dom 7:00-23:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.4,
        totalReviews: 56,
      },
      {
        id: '4-2',
        pharmacyId,
        name: 'Económicas Sur',
        address: 'Av. Morán Valverde N12-345',
        phone: '+593987660057',
        schedule: 'Lun-Dom 8:00-22:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.3,
        totalReviews: 48,
      },
      {
        id: '4-3',
        pharmacyId,
        name: 'Económicas Centro',
        address: 'Av. Pichincha N23-456',
        phone: '+593987660058',
        schedule: 'Lun-Sáb 7:30-21:30',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.5,
        totalReviews: 62,
      },
      {
        id: '4-4',
        pharmacyId,
        name: 'Económicas La Mariscal',
        address: 'Av. 6 de Diciembre N34-567',
        phone: '+593987660059',
        schedule: 'Lun-Dom 8:00-23:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.4,
        totalReviews: 51,
      },
      {
        id: '4-5',
        pharmacyId,
        name: 'Económicas Cumbayá',
        address: 'Vía Interoceánica Km 8.5',
        phone: '+593987660060',
        schedule: 'Lun-Dom 7:00-22:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.6,
        totalReviews: 43,
      },
      {
        id: '4-6',
        pharmacyId,
        name: 'Económicas Iñaquito',
        address: 'Av. Amazonas N56-789',
        phone: '+593987660061',
        schedule: 'Lun-Sáb 8:00-21:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.3,
        totalReviews: 39,
      },
      {
        id: '4-7',
        pharmacyId,
        name: 'Económicas Quicentro',
        address: 'Av. 6 de Diciembre N67-890',
        phone: '+593987660062',
        schedule: 'Lun-Dom 9:00-22:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.5,
        totalReviews: 47,
      },
      {
        id: '4-8',
        pharmacyId,
        name: 'Económicas La Carolina',
        address: 'Av. Naciones Unidas N78-901',
        phone: '+593987660063',
        schedule: 'Lun-Dom 7:30-21:30',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.4,
        totalReviews: 41,
      },
      {
        id: '4-9',
        pharmacyId,
        name: 'Económicas San Rafael',
        address: 'Av. 12 de Octubre N89-012',
        phone: '+593987660064',
        schedule: 'Lun-Sáb 8:00-20:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.5,
        totalReviews: 44,
      },
      {
        id: '4-10',
        pharmacyId,
        name: 'Económicas El Condado',
        address: 'Av. Mariana de Jesús N90-123',
        phone: '+593987660065',
        schedule: 'Lun-Dom 7:00-23:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.3,
        totalReviews: 38,
      },
      {
        id: '4-11',
        pharmacyId,
        name: 'Económicas La Prensa',
        address: 'Av. La Prensa N01-234',
        phone: '+593987660066',
        schedule: 'Lun-Dom 8:00-22:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.4,
        totalReviews: 42,
      },
      {
        id: '4-12',
        pharmacyId,
        name: 'Económicas Guayaquil',
        address: 'Av. 9 de Octubre N12-345',
        phone: '+593987660067',
        schedule: 'Lun-Sáb 7:30-21:00',
        hasDelivery: true,
        image: 'https://www.farmaenlace.com/wp-content/uploads/2022/07/farmacias_economicas-10.jpg',
        rating: 4.5,
        totalReviews: 40,
      },
    ],
    '5': [ // Pharmacy's
      {
        id: '5-1',
        pharmacyId,
        name: "Pharmacy's Quito",
        address: 'Av. Amazonas N45-123 y Av. Colón',
        phone: '+593987660068',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfNVLjpFiYcRIs8PA2fjnlpUJCcE-_D6jDyw&s',
        rating: 4.7,
        totalReviews: 33,
      },
      {
        id: '5-2',
        pharmacyId,
        name: "Pharmacy's Cumbayá",
        address: 'Av. Interoceánica Km 10',
        phone: '+593987660069',
        schedule: 'Lun-Sáb 8:30-20:30',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfNVLjpFiYcRIs8PA2fjnlpUJCcE-_D6jDyw&s',
        rating: 4.8,
        totalReviews: 41,
      },
      {
        id: '5-3',
        pharmacyId,
        name: "Pharmacy's La Mariscal",
        address: 'Av. 6 de Diciembre N56-234',
        phone: '+593987660070',
        schedule: 'Lun-Dom 9:00-22:00',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfNVLjpFiYcRIs8PA2fjnlpUJCcE-_D6jDyw&s',
        rating: 4.6,
        totalReviews: 28,
      },
      {
        id: '5-4',
        pharmacyId,
        name: "Pharmacy's Iñaquito",
        address: 'Av. Amazonas N67-345',
        phone: '+593987660071',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: false,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfNVLjpFiYcRIs8PA2fjnlpUJCcE-_D6jDyw&s',
        rating: 4.7,
        totalReviews: 35,
      },
      {
        id: '5-5',
        pharmacyId,
        name: "Pharmacy's Quicentro",
        address: 'Av. 6 de Diciembre N78-456',
        phone: '+593987660072',
        schedule: 'Lun-Sáb 8:30-21:30',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfNVLjpFiYcRIs8PA2fjnlpUJCcE-_D6jDyw&s',
        rating: 4.8,
        totalReviews: 39,
      },
      {
        id: '5-6',
        pharmacyId,
        name: "Pharmacy's La Carolina",
        address: 'Av. Naciones Unidas N89-567',
        phone: '+593987660073',
        schedule: 'Lun-Dom 8:00-20:00',
        hasDelivery: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfNVLjpFiYcRIs8PA2fjnlpUJCcE-_D6jDyw&s',
        rating: 4.7,
        totalReviews: 34,
      },
    ],
    '6': [ // Farmacia El Descuento
      {
        id: '6-1',
        pharmacyId,
        name: 'El Descuento Centro',
        address: 'Av. Pichincha N12-123',
        phone: '+593987660074',
        schedule: 'Lun-Dom 7:00-23:00',
        hasDelivery: true,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.5,
        totalReviews: 25,
      },
      {
        id: '6-2',
        pharmacyId,
        name: 'El Descuento Norte',
        address: 'Av. 10 de Agosto N23-234',
        phone: '+593987660075',
        schedule: 'Lun-Sáb 8:00-22:00',
        hasDelivery: true,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.4,
        totalReviews: 22,
      },
      {
        id: '6-3',
        pharmacyId,
        name: 'El Descuento Sur',
        address: 'Av. Morán Valverde N34-345',
        phone: '+593987660076',
        schedule: 'Lun-Dom 7:30-22:30',
        hasDelivery: true,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.6,
        totalReviews: 28,
      },
      {
        id: '6-4',
        pharmacyId,
        name: 'El Descuento La Mariscal',
        address: 'Av. 6 de Diciembre N45-456',
        phone: '+593987660077',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: false,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.5,
        totalReviews: 20,
      },
    ],
    '7': [ // Farmacias Sana Sana
      {
        id: '7-1',
        pharmacyId,
        name: 'Sana Sana Quito',
        address: 'Av. Amazonas N56-567',
        phone: '+593987660078',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.6,
        totalReviews: 42,
      },
      {
        id: '7-2',
        pharmacyId,
        name: 'Sana Sana Cumbayá',
        address: 'Vía Interoceánica Km 11',
        phone: '+593987660079',
        schedule: 'Lun-Sáb 8:30-20:30',
        hasDelivery: true,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.7,
        totalReviews: 38,
      },
      {
        id: '7-3',
        pharmacyId,
        name: 'Sana Sana La Mariscal',
        address: 'Av. 6 de Diciembre N67-678',
        phone: '+593987660080',
        schedule: 'Lun-Dom 9:00-22:00',
        hasDelivery: true,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.6,
        totalReviews: 35,
      },
      {
        id: '7-4',
        pharmacyId,
        name: 'Sana Sana Iñaquito',
        address: 'Av. Amazonas N78-789',
        phone: '+593987660081',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.8,
        totalReviews: 46,
      },
      {
        id: '7-5',
        pharmacyId,
        name: 'Sana Sana Quicentro',
        address: 'Av. 6 de Diciembre N89-890',
        phone: '+593987660082',
        schedule: 'Lun-Sáb 8:30-21:30',
        hasDelivery: true,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.7,
        totalReviews: 40,
      },
      {
        id: '7-6',
        pharmacyId,
        name: 'Sana Sana La Carolina',
        address: 'Av. Naciones Unidas N90-901',
        phone: '+593987660083',
        schedule: 'Lun-Dom 8:00-20:00',
        hasDelivery: false,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.6,
        totalReviews: 33,
      },
      {
        id: '7-7',
        pharmacyId,
        name: 'Sana Sana El Condado',
        address: 'Av. Mariana de Jesús N01-012',
        phone: '+593987660084',
        schedule: 'Lun-Dom 7:30-22:00',
        hasDelivery: true,
        image: 'https://gplaesperanza.gob.ec/wp-content/uploads/2025/05/491872692_1077347017758454_5398785111870776748_n.jpg',
        rating: 4.7,
        totalReviews: 36,
      },
    ],
    '8': [ // Farmacias El Cisne
      {
        id: '8-1',
        pharmacyId,
        name: 'El Cisne Quito',
        address: 'Av. Amazonas N12-123',
        phone: '+593987660085',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.8,
        totalReviews: 48,
      },
      {
        id: '8-2',
        pharmacyId,
        name: 'El Cisne Cumbayá',
        address: 'Vía Interoceánica Km 9',
        phone: '+593987660086',
        schedule: 'Lun-Sáb 8:30-20:30',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.9,
        totalReviews: 52,
      },
      {
        id: '8-3',
        pharmacyId,
        name: 'El Cisne La Mariscal',
        address: 'Av. 6 de Diciembre N23-234',
        phone: '+593987660087',
        schedule: 'Lun-Dom 9:00-22:00',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.8,
        totalReviews: 45,
      },
      {
        id: '8-4',
        pharmacyId,
        name: 'El Cisne Iñaquito',
        address: 'Av. Amazonas N34-345',
        phone: '+593987660088',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: false,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.7,
        totalReviews: 38,
      },
      {
        id: '8-5',
        pharmacyId,
        name: 'El Cisne Quicentro',
        address: 'Av. 6 de Diciembre N45-456',
        phone: '+593987660089',
        schedule: 'Lun-Sáb 8:30-21:30',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.8,
        totalReviews: 42,
      },
    ],
    '9': [ // Farmayor
      {
        id: '9-1',
        pharmacyId,
        name: 'Farmayor Quito',
        address: 'Av. Amazonas N56-567',
        phone: '+593987660090',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.7,
        totalReviews: 55,
      },
      {
        id: '9-2',
        pharmacyId,
        name: 'Farmayor Cumbayá',
        address: 'Vía Interoceánica Km 13',
        phone: '+593987660091',
        schedule: 'Lun-Sáb 8:30-20:30',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.8,
        totalReviews: 62,
      },
      {
        id: '9-3',
        pharmacyId,
        name: 'Farmayor La Mariscal',
        address: 'Av. 6 de Diciembre N67-678',
        phone: '+593987660092',
        schedule: 'Lun-Dom 9:00-22:00',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.7,
        totalReviews: 48,
      },
      {
        id: '9-4',
        pharmacyId,
        name: 'Farmayor Iñaquito',
        address: 'Av. Amazonas N78-789',
        phone: '+593987660093',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.6,
        totalReviews: 41,
      },
      {
        id: '9-5',
        pharmacyId,
        name: 'Farmayor Quicentro',
        address: 'Av. 6 de Diciembre N89-890',
        phone: '+593987660094',
        schedule: 'Lun-Sáb 8:30-21:30',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.8,
        totalReviews: 53,
      },
      {
        id: '9-6',
        pharmacyId,
        name: 'Farmayor La Carolina',
        address: 'Av. Naciones Unidas N90-901',
        phone: '+593987660095',
        schedule: 'Lun-Dom 8:00-20:00',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.7,
        totalReviews: 47,
      },
      {
        id: '9-7',
        pharmacyId,
        name: 'Farmayor El Condado',
        address: 'Av. Mariana de Jesús N01-012',
        phone: '+593987660096',
        schedule: 'Lun-Dom 7:30-22:00',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.8,
        totalReviews: 50,
      },
      {
        id: '9-8',
        pharmacyId,
        name: 'Farmayor La Prensa',
        address: 'Av. La Prensa N12-123',
        phone: '+593987660097',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: false,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.7,
        totalReviews: 44,
      },
      {
        id: '9-9',
        pharmacyId,
        name: 'Farmayor Guayaquil',
        address: 'Av. 9 de Octubre N23-234',
        phone: '+593987660098',
        schedule: 'Lun-Sáb 8:00-20:00',
        hasDelivery: true,
        image: 'https://bbxmusic.com/press/wp-content/uploads/2016/06/Image13-1024x473.jpg',
        rating: 4.6,
        totalReviews: 39,
      },
    ],
    '10': [ // Farmacias Cruz Azul
      {
        id: '10-1',
        pharmacyId,
        name: 'Cruz Azul Quito',
        address: 'Av. Amazonas N34-345',
        phone: '+593987660099',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://queondagye.com/wp-content/uploads/2023/07/Cruz-Azul-1024x707.jpg',
        rating: 4.5,
        totalReviews: 32,
      },
      {
        id: '10-2',
        pharmacyId,
        name: 'Cruz Azul Cumbayá',
        address: 'Vía Interoceánica Km 7',
        phone: '+593987660100',
        schedule: 'Lun-Sáb 8:30-20:30',
        hasDelivery: true,
        image: 'https://queondagye.com/wp-content/uploads/2023/07/Cruz-Azul-1024x707.jpg',
        rating: 4.6,
        totalReviews: 38,
      },
      {
        id: '10-3',
        pharmacyId,
        name: 'Cruz Azul La Mariscal',
        address: 'Av. 6 de Diciembre N45-456',
        phone: '+593987660101',
        schedule: 'Lun-Dom 9:00-22:00',
        hasDelivery: true,
        image: 'https://queondagye.com/wp-content/uploads/2023/07/Cruz-Azul-1024x707.jpg',
        rating: 4.5,
        totalReviews: 35,
      },
      {
        id: '10-4',
        pharmacyId,
        name: 'Cruz Azul Iñaquito',
        address: 'Av. Amazonas N56-567',
        phone: '+593987660102',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: false,
        image: 'https://queondagye.com/wp-content/uploads/2023/07/Cruz-Azul-1024x707.jpg',
        rating: 4.6,
        totalReviews: 29,
      },
      {
        id: '10-5',
        pharmacyId,
        name: 'Cruz Azul Quicentro',
        address: 'Av. 6 de Diciembre N67-678',
        phone: '+593987660103',
        schedule: 'Lun-Sáb 8:30-21:30',
        hasDelivery: true,
        image: 'https://queondagye.com/wp-content/uploads/2023/07/Cruz-Azul-1024x707.jpg',
        rating: 4.5,
        totalReviews: 31,
      },
      {
        id: '10-6',
        pharmacyId,
        name: 'Cruz Azul La Carolina',
        address: 'Av. Naciones Unidas N78-789',
        phone: '+593987660104',
        schedule: 'Lun-Dom 8:00-20:00',
        hasDelivery: true,
        image: 'https://queondagye.com/wp-content/uploads/2023/07/Cruz-Azul-1024x707.jpg',
        rating: 4.6,
        totalReviews: 34,
      },
    ],
    '11': [ // Farmacias San Gregorio
      {
        id: '11-1',
        pharmacyId,
        name: 'San Gregorio Quito',
        address: 'Av. Amazonas N89-890',
        phone: '+593987660105',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://ecuadorempleos.org/wp-content/uploads/2024/11/farmacias-san-gregorio.jpg',
        rating: 4.6,
        totalReviews: 28,
      },
      {
        id: '11-2',
        pharmacyId,
        name: 'San Gregorio Cumbayá',
        address: 'Vía Interoceánica Km 14',
        phone: '+593987660106',
        schedule: 'Lun-Sáb 8:30-20:30',
        hasDelivery: true,
        image: 'https://ecuadorempleos.org/wp-content/uploads/2024/11/farmacias-san-gregorio.jpg',
        rating: 4.7,
        totalReviews: 35,
      },
      {
        id: '11-3',
        pharmacyId,
        name: 'San Gregorio La Mariscal',
        address: 'Av. 6 de Diciembre N90-901',
        phone: '+593987660107',
        schedule: 'Lun-Dom 9:00-22:00',
        hasDelivery: true,
        image: 'https://ecuadorempleos.org/wp-content/uploads/2024/11/farmacias-san-gregorio.jpg',
        rating: 4.6,
        totalReviews: 32,
      },
      {
        id: '11-4',
        pharmacyId,
        name: 'San Gregorio Iñaquito',
        address: 'Av. Amazonas N01-012',
        phone: '+593987660108',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: false,
        image: 'https://ecuadorempleos.org/wp-content/uploads/2024/11/farmacias-san-gregorio.jpg',
        rating: 4.7,
        totalReviews: 27,
      },
    ],
    '12': [ // Farmacias Salud Total
      {
        id: '12-1',
        pharmacyId,
        name: 'Salud Total Quito',
        address: 'Av. Amazonas N12-123',
        phone: '+593987660109',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://www.agenciapi.co/sites/default/files/styles/imagen_principal_contenidos_2021/public/2024-08/SALUD%20TOTAL%2014%20AGOSTO.jpg.webp?itok=b-tTYPV0',
        rating: 4.7,
        totalReviews: 58,
      },
      {
        id: '12-2',
        pharmacyId,
        name: 'Salud Total Cumbayá',
        address: 'Vía Interoceánica Km 15',
        phone: '+593987660110',
        schedule: 'Lun-Sáb 8:30-20:30',
        hasDelivery: true,
        image: 'https://www.agenciapi.co/sites/default/files/styles/imagen_principal_contenidos_2021/public/2024-08/SALUD%20TOTAL%2014%20AGOSTO.jpg.webp?itok=b-tTYPV0',
        rating: 4.8,
        totalReviews: 64,
      },
      {
        id: '12-3',
        pharmacyId,
        name: 'Salud Total La Mariscal',
        address: 'Av. 6 de Diciembre N23-234',
        phone: '+593987660111',
        schedule: 'Lun-Dom 9:00-22:00',
        hasDelivery: true,
        image: 'https://www.agenciapi.co/sites/default/files/styles/imagen_principal_contenidos_2021/public/2024-08/SALUD%20TOTAL%2014%20AGOSTO.jpg.webp?itok=b-tTYPV0',
        rating: 4.7,
        totalReviews: 52,
      },
      {
        id: '12-4',
        pharmacyId,
        name: 'Salud Total Iñaquito',
        address: 'Av. Amazonas N34-345',
        phone: '+593987660112',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://www.agenciapi.co/sites/default/files/styles/imagen_principal_contenidos_2021/public/2024-08/SALUD%20TOTAL%2014%20AGOSTO.jpg.webp?itok=b-tTYPV0',
        rating: 4.8,
        totalReviews: 59,
      },
      {
        id: '12-5',
        pharmacyId,
        name: 'Salud Total Quicentro',
        address: 'Av. 6 de Diciembre N45-456',
        phone: '+593987660113',
        schedule: 'Lun-Sáb 8:30-21:30',
        hasDelivery: true,
        image: 'https://www.agenciapi.co/sites/default/files/styles/imagen_principal_contenidos_2021/public/2024-08/SALUD%20TOTAL%2014%20AGOSTO.jpg.webp?itok=b-tTYPV0',
        rating: 4.7,
        totalReviews: 55,
      },
      {
        id: '12-6',
        pharmacyId,
        name: 'Salud Total La Carolina',
        address: 'Av. Naciones Unidas N56-567',
        phone: '+593987660114',
        schedule: 'Lun-Dom 8:00-20:00',
        hasDelivery: true,
        image: 'https://www.agenciapi.co/sites/default/files/styles/imagen_principal_contenidos_2021/public/2024-08/SALUD%20TOTAL%2014%20AGOSTO.jpg.webp?itok=b-tTYPV0',
        rating: 4.8,
        totalReviews: 61,
      },
      {
        id: '12-7',
        pharmacyId,
        name: 'Salud Total El Condado',
        address: 'Av. Mariana de Jesús N67-678',
        phone: '+593987660115',
        schedule: 'Lun-Dom 7:30-22:00',
        hasDelivery: true,
        image: 'https://www.agenciapi.co/sites/default/files/styles/imagen_principal_contenidos_2021/public/2024-08/SALUD%20TOTAL%2014%20AGOSTO.jpg.webp?itok=b-tTYPV0',
        rating: 4.7,
        totalReviews: 48,
      },
      {
        id: '12-8',
        pharmacyId,
        name: 'Salud Total La Prensa',
        address: 'Av. La Prensa N78-789',
        phone: '+593987660116',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: false,
        image: 'https://www.agenciapi.co/sites/default/files/styles/imagen_principal_contenidos_2021/public/2024-08/SALUD%20TOTAL%2014%20AGOSTO.jpg.webp?itok=b-tTYPV0',
        rating: 4.8,
        totalReviews: 54,
      },
      {
        id: '12-9',
        pharmacyId,
        name: 'Salud Total Guayaquil',
        address: 'Av. 9 de Octubre N89-890',
        phone: '+593987660117',
        schedule: 'Lun-Sáb 8:00-20:00',
        hasDelivery: true,
        image: 'https://www.agenciapi.co/sites/default/files/styles/imagen_principal_contenidos_2021/public/2024-08/SALUD%20TOTAL%2014%20AGOSTO.jpg.webp?itok=b-tTYPV0',
        rating: 4.7,
        totalReviews: 47,
      },
      {
        id: '12-10',
        pharmacyId,
        name: 'Salud Total Cuenca',
        address: 'Av. Gran Colombia N90-901',
        phone: '+593987660118',
        schedule: 'Lun-Dom 8:00-21:00',
        hasDelivery: true,
        image: 'https://www.agenciapi.co/sites/default/files/styles/imagen_principal_contenidos_2021/public/2024-08/SALUD%20TOTAL%2014%20AGOSTO.jpg.webp?itok=b-tTYPV0',
        rating: 4.8,
        totalReviews: 51,
      },
    ],
  };

  // Retornar las sucursales correspondientes a la farmacia o un array vacío
  return branchesByPharmacy[pharmacyId] || [];
};

/**
 * API: Obtener detalle de una sucursal
 * TODO: Conectar con endpoint real del backend cuando esté disponible
 * Endpoint esperado: GET /api/pharmacy-branches/:id
 */
export const getBranchAPI = async (branchId: string): Promise<PharmacyBranch> => {
  // TODO: Reemplazar con llamada real al backend
  // const response = await httpClient.get<PharmacyBranch>(`/pharmacy-branches/${branchId}`);
  // return response.data;

  // NOTE: Datos mock por ahora - buscar en todas las sucursales de todas las farmacias
  const allPharmacies = await getPharmaciesAPI();
  
  // Buscar la sucursal en todas las farmacias
  for (const pharmacy of allPharmacies) {
    const branches = await getPharmacyBranchesAPI(pharmacy.id);
    const branch = branches.find((b) => b.id === branchId);
    if (branch) {
      return branch;
    }
  }

  // Fallback si no se encuentra
  return {
    id: branchId,
    pharmacyId: '1',
    name: 'Medicity Cumbayá',
    address: 'Vía Interoceánica Km 12.5',
    phone: '+593987660042',
    schedule: 'Lun-Dom 8:30-21:00',
    hasDelivery: true,
    image: 'https://fastly.4sqi.net/img/general/320x240/61607334_pJHR8VPjSpzwPBjtU6GjRzBYk-ly4_76BEyvRjjVkbc.jpg',
    rating: 4.7,
    totalReviews: 38,
  };
};

/**
 * API: Obtener reseñas de una sucursal
 * TODO: Conectar con endpoint real del backend cuando esté disponible
 * Endpoint esperado: GET /api/pharmacy-branches/:id/reviews
 */
export const getBranchReviewsAPI = async (branchId: string): Promise<Review[]> => {
  // TODO: Reemplazar con llamada real al backend
  // const response = await httpClient.get<Review[]>(`/pharmacy-branches/${branchId}/reviews`);
  // return response.data;

  // NOTE: Datos mock por ahora - almacenar en localStorage para persistencia
  const storedReviews = localStorage.getItem(`reviews_${branchId}`);
  if (storedReviews) {
    return JSON.parse(storedReviews);
  }
  return [];
};

/**
 * API: Crear una reseña
 * TODO: Conectar con endpoint real del backend cuando esté disponible
 * Endpoint esperado: POST /api/pharmacy-branches/:id/reviews
 */
export const createReviewAPI = async (params: { branchId: string; rating: number; comment?: string }): Promise<Review> => {
  // TODO: Reemplazar con llamada real al backend
  // const response = await httpClient.post<Review>(`/pharmacy-branches/${params.branchId}/reviews`, params);
  // return response.data;

  // NOTE: Datos mock por ahora - guardar en localStorage
  const existingReviews = await getBranchReviewsAPI(params.branchId);
  
  // Obtener usuario desde localStorage
  const savedUser = localStorage.getItem('auth-user');
  let userId = 'user_1';
  let userName = 'Usuario';
  if (savedUser) {
    try {
      const user = JSON.parse(savedUser);
      userId = user.id || userId;
      userName = user.name || userName;
    } catch (error) {
      console.error('Error al parsear usuario:', error);
    }
  }
  
  const newReview: Review = {
    id: `review_${Date.now()}`,
    branchId: params.branchId,
    userId,
    userName,
    rating: params.rating,
    comment: params.comment,
    createdAt: new Date().toISOString(),
  };

  const updatedReviews = [...existingReviews, newReview];
  localStorage.setItem(`reviews_${params.branchId}`, JSON.stringify(updatedReviews));

  return newReview;
};

